version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4566:4566"
    environment:
      PRISMA_CONFIG: |
        port: 4566
        databases:
          default:
            connector: mysql
            host: ${PRISMA_HOST}
            port: 3306
            user: root
            migrations: true
            rawAccess: true
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
